src/SunBlog.AspNetCore/Z.SunBlog.Host/Models/ErrorViewModel.cs
namespace Z.SunBlog.Host.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/SunBlog.AspNetCore/Z.SunBlog.Host/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Z.Ddd.Common.Attributes;
using Z.Ddd.Common.Helper;
using Z.SunBlog.Application.UserModule;
using Z.SunBlog.Host.Models;

namespace Z.SunBlog.Host.Controllers
{
    [NoResult]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserAppService userRespo;

        public HomeController(ILogger<HomeController> logger,  IUserAppService userRespo)
        {
            _logger = logger;
            this.userRespo = userRespo;
        }
        public async Task<IActionResult> Index()
        {
            if (AppSettings.Environment().IsDevelopment())
            {
                ViewBag.Url = "http://localhost:5155";
            }
            else
            {
                ViewBag.Url = "http://101.201.118.85:5155";
            }
            
            _logger.LogInformation("正在加载首页......");
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SunBlog.AspNetCore/Z.SunBlog.Host/Controllers/TestController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Z.Ddd.Common.Authorization;
using Z.Ddd.Common.UserSession;
using Z.SunBlog.Application.UserModule;
using Serilog;
using Z.Ddd.Common.RedisModule;
using Z.SunBlog.Application.UserModule.Dto;
using Z.Ddd.Common.Exceptions;
using Z.Ddd.Common;
using Z.Ddd.Common.Helper;

namespace Z.SunBlog.Host.Controllers
{
    /// <summary>
    /// 测试控制器
    /// </summary>
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class TestController : ControllerBase
    {
        private readonly IJwtTokenProvider _jwtTokenProvider;
        private readonly IUserSession _userSession;
        private readonly IUserAppService _userAppService;
        private ICacheManager _cacheManager;
        public TestController(IJwtTokenProvider jwtTokenProvider, IUserSession userSession, IUserAppService userAppService, ICacheManager cacheManager)
        {
            _jwtTokenProvider = jwtTokenProvider;
            _userSession = userSession;
            _userAppService = userAppService;
            _cacheManager = cacheManager;
        }





        /// <summary>
        /// 获取jwttoken
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<string> Login(ZUserInfoDto user)
        {
            var userinfo = await _userAppService.Login(user);
            if (userinfo == null)
            {
                throw new UserFriendlyException("账号密码错误");

            }
            var tokenConfig = AppSettings.AppOption<JwtSettings>("App:JWtSetting");
            // 设置Token的Claims
            List<Claim> claims = new List<Claim>
            {
               new Claim(ZClaimTypes.UserName, userinfo.UserName!), //HttpContext.User.Identity.Name
                new Claim(ZClaimTypes.UserId, userinfo.Id!.ToString()),
                new Claim(ZClaimTypes.Expiration, DateTimeOffset.Now.AddMinutes(tokenConfig.AccessTokenExpirationMinutes).ToString()),
            };
            var token = _jwtTokenProvider.GenerateZToken(claims.ToArray());

            Response.Cookies.Append("access-token", token.AccessToken, new CookieOptions()
            {
                Expires = DateTimeOffset.UtcNow.AddMinutes(20)
             });

            Log.Logger.Information("登录成功");
            return token.AccessToken;
        }


        /// <summary>
        /// 获取jwttoken
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ZAuthorization]
        public async Task<string> GetUser()
        {
            var user = _userSession.UserName;
            var userid = _userSession.UserId;

            return user;
        }

        [HttpGet]
        public async Task<string> Logout()
        {

            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return "ddd";
        }

        /// <summary>
        /// 创建用户
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ZAuthorization]
        public async Task<JsonResult> CreateUser()
        {
            return new JsonResult(await _userAppService.Create());
        }

        /// <summary>
        /// 获取用户
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ZAuthorization]
        public async Task<List<ZUserInfoDto>> SeacthUser()
        {

            var user = await _userAppService.GetFrist();

            await _cacheManager.SetCacheAsync("user1", user);

            return user;
        }


        /// <summary>
        /// 获取用户
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ZAuthorization]
        public async Task<List<ZUserInfoDto>> SeacthUserCache()
        {

            var user = await _cacheManager.GetCacheAsync<List<ZUserInfoDto>>("user1");

            return user;
        }

    }
}

src/SunBlog.AspNetCore/Z.SunBlog.Host/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Fantasy-Ke";
}

<div>
    <div class="login-box">
        <h2>登录</h2>
        <form>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">用户名:</span>
                </div>
                <input type="text" id="username" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">密码:</span>
                </div>
                <input type="password" id="password" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
            </div>

        </form>
        <button type="submit" id="login-btn" class="btn btn-primary">登录</button>
    </div>
    @*  <div>
    <a asp-controller="Test" asp-action="GetToken">登陆</a>
    </div> *@
    <button type="button" hidden class="btn btn-primary" id="whatever" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="mdo"></button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">错误！</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="word-wrap:break-word;">
                </div>
            </div>
        </div>
    </div>
</div>




<script>
    $(document).ready(function () {
        // 当表单提交时
        $('#login-btn').click(function (event) {
            event.preventDefault(); // 防止页面刷新
            //$('.error').remove(); // 移除已有的错误信息
            var username = $('#username').val();
            var password = $('#password').val();
            // 发起 AJAX 请求
            $.ajax({
                type: 'post',
                contentType: "application/json",
                url: '@ViewBag.Url/api/Test/Login',
                data: JSON.stringify({
                    username: username,
                    password: password
                }),
                success: function (response) {
                    console.info(response)
                    if (response.statusCode == '200') {
                        window.location.href = '/swagger';
                    }
                },
                error: function (response) {
                    // 如果返回错误信息，则显示在页面上
                    const exampleModal = document.getElementById('exampleModal')
                    exampleModal.addEventListener('show.bs.modal', event => {
                        // Update the modal's content.
                        const modalTitle = exampleModal.querySelector('.modal-title');
                        const modalBodyInput = exampleModal.querySelector('.modal-body');

                        modalBodyInput.textContent = response?.responseJSON?.result?.error ?? '服务器异常';
                    })
                    $('#whatever').trigger('click');

                }
            });
        });
    });

</script>

<style>
    .login-box {
        /* background-color: #fff; */
        background-color: rgba(255,255,255,0.4);
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
        margin: 0px auto;
        padding: 20px;
        text-align: center;
        width: 350px;
    }

        .login-box h2 {
            margin: 0 0 20px;
        }

    .user-box {
        margin-bottom: 20px;
        text-align: left;
    }

        .user-box label {
            display: block;
            margin-bottom: 5px;
        }

        .user-box input {
            border: none;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            padding: 10px;
            width: 100%;
        }

    button {
        background-color: #4CAF50;
        border: none;
        border-radius: 5px;
        color: #fff;
        cursor: pointer;
        padding: 10px;
        width: 100%;
    }

        button:hover {
            background-color: #3e8e41;
        }

    .error {
        color: red;
        font-size: 12px;
        margin-top: 5px;
    }

</style>

src/SunBlog.AspNetCore/Z.SunBlog.Host/Views/Master/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<p>这是一个段落</p>
<h4>测试</h4>
<h5>再加一个测试</h5>

src/SunBlog.AspNetCore/Z.SunBlog.Host/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Z.SunBlog.Host</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="icon" href="~/favicon.ico">
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <el-container class="el-container">
        <el-header></el-header>
        <el-main class="el-main"> @RenderBody()</el-main>
        <el-footer></el-footer>
    </el-container>
</body>
</html>